export const LANDING_PAGE_URL = '/'
export const MY_SHOPS_URL = '/rest/my_shops'
export const SIGN_UP_PAGE_URL = '/signup'
export const SHOPS_URL = '/rest/shops'
export const SIGN_UP_URL = '/rest/signup'
export const LOG_IN_URL = '/rest/login'
