export const POST_URL = '/rest/post'
export const POSTS_URL = '/rest/posts'
export const LOGIN_URL = '/rest/login'
export const LIKE_POST_URL = '/rest/post/like'
export const LIKE_STORE_URL = '/rest/store/like'
export const STORE_URL = '/rest/store'