runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:

- url: /bundle\.js
  static_files: bundle.js
  upload: bundle\.js

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /rest/posts
  script: backend.backend.app

- url: /.*
  script: backend.backend.app

- url: /*
  script: backend.backend.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: 2.5.1
- name: jinja2
  version: latest
# [END libraries]

builtins:
- remote_api: on

env_variables:
    CLOUD_STORAGE_BUCKET: lighthouse-149319.appspot.com
